config/routes.rb
Dinner4two::Application.routes.draw do



  if Rails.env.development?  

    %w[cash_payment credit_card_payment].each do |sti_model|
      require_dependency File.join("app", "models", "#{sti_model}.rb") 
    end  
  end  


  def delegate_descandants klass, controller_name = nil

    controller_name ||= klass.name.demodulize.pluralize.underscore

    klass.descendants.each do |sub_klass|
      resources sub_klass.model_name.demodulize.pluralize.underscore.to_sym, controller: controller_name
    end  
  end  

  
  resources :bills
  resources :orders
  resources :drinks
  resources :dishes
  resources :tables
  resources :reservations
  resources :guests

  resources :payments do
    delegate_descandants CashPayment
    delegate_descandants CreditCardPayment
  end  




  get "home/index"

  root :to => 'home#index'












end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :discount, :guest_id, :order_sum, :paid, :tax, :total

  belongs_to :guest
  has_one :payment
  has_many :orders

end

app/models/cash_payment.rb
class CashPayment < Payment

end	

app/models/credit_card_payment.rb
class CreditCardPayment < Payment

end	

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :description, :notes, :number, :price, :title

  has_many :orders, as: :item

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :alcoholic, :number, :price, :size, :title

  has_many :orders, as: :item

end

app/models/guest.rb
# -*- encoding : utf-8 -*-
class Guest < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :first_name, :last_name, :postal, :telefon

  has_many :reservations
  has_many :orders
  has_many :bills
  has_many :payments, through: :bills


  def fullname
  	"#{first_name} #{last_name}"
  end	


end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bill_id, :cancelled, :discount, :guest_id, :item_id, :item_type, :position, :price, :reservation_id, :product_name

  belongs_to :guest
  belongs_to :reservation
  belongs_to :bill

  belongs_to :item, polymorphic: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :bill_id, :card_number, :card_provider, :card_valid_until, :paid_at, :total, :type

  belongs_to :bill
  has_one :guest, through: :bill

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :duration, :guest_id, :notes, :priority, :reservation_date, :special_service

  belongs_to :guest
  has_one :table
  has_many :orders
  

end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :exclusive, :number, :reservation_id, :seats, :taken

  belongs_to :reservation

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/guests_controller.rb
# -*- encoding : utf-8 -*-
class GuestsController < ApplicationController
  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @guests }
    end
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
    @guest = Guest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/new
  # GET /guests/new.json
  def new
    @guest = Guest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @guest }
    end
  end

  # GET /guests/1/edit
  def edit
    @guest = Guest.find(params[:id])
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(params[:guest])

    respond_to do |format|
      if @guest.save
        format.html { redirect_to @guest, notice: 'Guest was successfully created.' }
        format.json { render json: @guest, status: :created, location: @guest }
      else
        format.html { render action: "new" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /guests/1
  # PUT /guests/1.json
  def update
    @guest = Guest.find(params[:id])

    respond_to do |format|
      if @guest.update_attributes(params[:guest])
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy

    respond_to do |format|
      format.html { redirect_to guests_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/guests_helper.rb
# -*- encoding : utf-8 -*-
module GuestsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :postal %><br />
    <%= f.number_field :postal %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :telefon %><br />
    <%= f.text_field :telefon %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1>Editing guest</h1>

<%= render 'form' %>

<%= link_to 'Show', @guest %> |
<%= link_to 'Back', guests_path %>

app/views/guests/index.html.erb
<h1>Listing guests</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>Postal</th>
    <th>City</th>
    <th>Country</th>
    <th>Telefon</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @guests.each do |guest| %>
  <tr>
    <td><%= guest.first_name %></td>
    <td><%= guest.last_name %></td>
    <td><%= guest.address %></td>
    <td><%= guest.postal %></td>
    <td><%= guest.city %></td>
    <td><%= guest.country %></td>
    <td><%= guest.telefon %></td>
    <td><%= guest.email %></td>
    <td><%= link_to 'Show', guest %></td>
    <td><%= link_to 'Edit', edit_guest_path(guest) %></td>
    <td><%= link_to 'Destroy', guest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Guest', new_guest_path %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @guest.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @guest.last_name %>
</p>

<p>
  <b>Address:</b>
  <%= @guest.address %>
</p>

<p>
  <b>Postal:</b>
  <%= @guest.postal %>
</p>

<p>
  <b>City:</b>
  <%= @guest.city %>
</p>

<p>
  <b>Country:</b>
  <%= @guest.country %>
</p>

<p>
  <b>Telefon:</b>
  <%= @guest.telefon %>
</p>

<p>
  <b>Email:</b>
  <%= @guest.email %>
</p>


<%= link_to 'Edit', edit_guest_path(@guest) %> |
<%= link_to 'Back', guests_path %>