config/routes.rb
Dinner4two::Application.routes.draw do



  if Rails.env.development?  

    %w[cash_payment credit_card_payment].each do |sti_model|
      require_dependency File.join("app", "models", "#{sti_model}.rb") 
    end  
  end  


  def delegate_descandants klass, controller_name = nil

    controller_name ||= klass.name.demodulize.pluralize.underscore

    klass.descendants.each do |sub_klass|
      resources sub_klass.model_name.demodulize.pluralize.underscore.to_sym, controller: controller_name
    end  
  end  

  
  resources :bills
  resources :orders
  resources :drinks
  resources :dishes
  resources :tables
  resources :reservations
  resources :guests

  resources :payments do
    delegate_descandants CashPayment
    delegate_descandants CreditCardPayment
  end  




  get "home/index"

  root :to => 'home#index'












end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :discount, :guest_id, :order_sum, :paid, :tax, :total

  belongs_to :guest
  has_one :payment
  has_many :orders

end

app/models/cash_payment.rb
class CashPayment < Payment

end	

app/models/credit_card_payment.rb
class CreditCardPayment < Payment

end	

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :description, :notes, :number, :price, :title

  has_many :orders, as: :item

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :alcoholic, :number, :price, :size, :title

  has_many :orders, as: :item

end

app/models/guest.rb
# -*- encoding : utf-8 -*-
class Guest < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :first_name, :last_name, :postal, :telefon

  has_many :reservations
  has_many :orders
  has_many :bills
  has_many :payments, through: :bills


  def fullname
  	"#{first_name} #{last_name}"
  end	


end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bill_id, :cancelled, :discount, :guest_id, :item_id, :item_type, :position, :price, :reservation_id, :product_name

  belongs_to :guest
  belongs_to :reservation
  belongs_to :bill

  belongs_to :item, polymorphic: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :bill_id, :card_number, :card_provider, :card_valid_until, :paid_at, :total, :type

  belongs_to :bill
  has_one :guest, through: :bill

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :duration, :guest_id, :notes, :priority, :reservation_date, :special_service

  belongs_to :guest
  has_one :table
  has_many :orders
  

end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :exclusive, :number, :reservation_id, :seats, :taken

  belongs_to :reservation

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  # GET /dishes
  # GET /dishes.json
  def index
    @dishes = Dish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dishes }
    end
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
    @dish = Dish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/new
  # GET /dishes/new.json
  def new
    @dish = Dish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dish }
    end
  end

  # GET /dishes/1/edit
  def edit
    @dish = Dish.find(params[:id])
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.new(params[:dish])

    respond_to do |format|
      if @dish.save
        format.html { redirect_to @dish, notice: 'Dish was successfully created.' }
        format.json { render json: @dish, status: :created, location: @dish }
      else
        format.html { render action: "new" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dishes/1
  # PUT /dishes/1.json
  def update
    @dish = Dish.find(params[:id])

    respond_to do |format|
      if @dish.update_attributes(params[:dish])
        format.html { redirect_to @dish, notice: 'Dish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dishes/1
  # DELETE /dishes/1.json
  def destroy
    @dish = Dish.find(params[:id])
    @dish.destroy

    respond_to do |format|
      format.html { redirect_to dishes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/guests_helper.rb
# -*- encoding : utf-8 -*-
module GuestsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :guest_id %>
    <%= f.input :order_sum %>
    <%= f.input :discount %>
    <%= f.input :total %>
    <%= f.input :tax %>
    <%= f.input :paid %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Guest</th>
    <th>Order sum</th>
    <th>Discount</th>
    <th>Total</th>
    <th>Tax</th>
    <th>Paid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td><%= bill.guest_id %></td>
    <td><%= bill.order_sum %></td>
    <td><%= bill.discount %></td>
    <td><%= bill.total %></td>
    <td><%= bill.tax %></td>
    <td><%= bill.paid %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Guest:</b>
  <%= @bill.guest_id %>
</p>

<p>
  <b>Order sum:</b>
  <%= @bill.order_sum %>
</p>

<p>
  <b>Discount:</b>
  <%= @bill.discount %>
</p>

<p>
  <b>Total:</b>
  <%= @bill.total %>
</p>

<p>
  <b>Tax:</b>
  <%= @bill.tax %>
</p>

<p>
  <b>Paid:</b>
  <%= @bill.paid %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/dishes/_form.html.erb
<%= simple_form_for(@dish) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :number %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Editing dish</h1>

<%= render 'form' %>

<%= link_to 'Show', @dish %> |
<%= link_to 'Back', dishes_path %>

app/views/dishes/index.html.erb
<h1>Listing dishes</h1>

<table>
  <tr>
    <th>Number</th>
    <th>Title</th>
    <th>Description</th>
    <th>Price</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dishes.each do |dish| %>
  <tr>
    <td><%= dish.number %></td>
    <td><%= dish.title %></td>
    <td><%= dish.description %></td>
    <td><%= dish.price %></td>
    <td><%= dish.notes %></td>
    <td><%= link_to 'Show', dish %></td>
    <td><%= link_to 'Edit', edit_dish_path(dish) %></td>
    <td><%= link_to 'Destroy', dish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dish', new_dish_path %>

app/views/dishes/new.html.erb
<h1>New dish</h1>

<%= render 'form' %>

<%= link_to 'Back', dishes_path %>

app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @dish.number %>
</p>

<p>
  <b>Title:</b>
  <%= @dish.title %>
</p>

<p>
  <b>Description:</b>
  <%= @dish.description %>
</p>

<p>
  <b>Price:</b>
  <%= @dish.price %>
</p>

<p>
  <b>Notes:</b>
  <%= @dish.notes %>
</p>


<%= link_to 'Edit', edit_dish_path(@dish) %> |
<%= link_to 'Back', dishes_path %>