config/routes.rb
Dinner4two::Application.routes.draw do



  if Rails.env.development?  

    %w[cash_payment credit_card_payment].each do |sti_model|
      require_dependency File.join("app", "models", "#{sti_model}.rb") 
    end  
  end  


  def delegate_descandants klass, controller_name = nil

    controller_name ||= klass.name.demodulize.pluralize.underscore

    klass.descendants.each do |sub_klass|
      resources sub_klass.model_name.demodulize.pluralize.underscore.to_sym, controller: controller_name
    end  
  end  

  
  resources :bills
  resources :orders
  resources :drinks
  resources :dishes
  resources :tables
  resources :reservations
  resources :guests

  resources :payments do
    delegate_descandants CashPayment
    delegate_descandants CreditCardPayment
  end  




  get "home/index"

  root :to => 'home#index'












end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :discount, :guest_id, :order_sum, :paid, :tax, :total

  belongs_to :guest
  has_one :payment
  has_many :orders

end

app/models/cash_payment.rb
class CashPayment < Payment

end	

app/models/credit_card_payment.rb
class CreditCardPayment < Payment

end	

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :description, :notes, :number, :price, :title

  has_many :orders, as: :item

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :alcoholic, :number, :price, :size, :title

  has_many :orders, as: :item

end

app/models/guest.rb
# -*- encoding : utf-8 -*-
class Guest < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :first_name, :last_name, :postal, :telefon

  has_many :reservations
  has_many :orders
  has_many :bills
  has_many :payments, through: :bills


  def fullname
  	"#{first_name} #{last_name}"
  end	


end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bill_id, :cancelled, :discount, :guest_id, :item_id, :item_type, :position, :price, :reservation_id, :product_name

  belongs_to :guest
  belongs_to :reservation
  belongs_to :bill

  belongs_to :item, polymorphic: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :bill_id, :card_number, :card_provider, :card_valid_until, :paid_at, :total, :type

  belongs_to :bill
  has_one :guest, through: :bill

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :duration, :guest_id, :notes, :priority, :reservation_date, :special_service

  belongs_to :guest
  has_one :table
  has_many :orders
  

end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :exclusive, :number, :reservation_id, :seats, :taken

  belongs_to :reservation

end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/guests_helper.rb
# -*- encoding : utf-8 -*-
module GuestsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= simple_form_for(@table) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :reservation_id %>
    <%= f.input :number %>
    <%= f.input :seats %>
    <%= f.input :exclusive %>
    <%= f.input :taken %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Reservation</th>
    <th>Number</th>
    <th>Seats</th>
    <th>Exclusive</th>
    <th>Taken</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.reservation_id %></td>
    <td><%= table.number %></td>
    <td><%= table.seats %></td>
    <td><%= table.exclusive %></td>
    <td><%= table.taken %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Reservation:</b>
  <%= @table.reservation_id %>
</p>

<p>
  <b>Number:</b>
  <%= @table.number %>
</p>

<p>
  <b>Seats:</b>
  <%= @table.seats %>
</p>

<p>
  <b>Exclusive:</b>
  <%= @table.exclusive %>
</p>

<p>
  <b>Taken:</b>
  <%= @table.taken %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>