config/routes.rb
Dinner4two::Application.routes.draw do



  if Rails.env.development?  

    %w[cash_payment credit_card_payment].each do |sti_model|
      require_dependency File.join("app", "models", "#{sti_model}.rb") 
    end  
  end  


  def delegate_descandants klass, controller_name = nil

    controller_name ||= klass.name.demodulize.pluralize.underscore

    klass.descendants.each do |sub_klass|
      resources sub_klass.model_name.demodulize.pluralize.underscore.to_sym, controller: controller_name
    end  
  end  

  
  resources :bills
  resources :orders
  resources :drinks
  resources :dishes
  resources :tables
  resources :reservations
  resources :guests

  resources :payments do
    delegate_descandants CashPayment
    delegate_descandants CreditCardPayment
  end  




  get "home/index"

  root :to => 'home#index'












end

app/models/bill.rb
class Bill < ActiveRecord::Base
  attr_accessible :discount, :guest_id, :order_sum, :paid, :tax, :total

  belongs_to :guest
  has_one :payment
  has_many :orders

end

app/models/cash_payment.rb
class CashPayment < Payment

end	

app/models/credit_card_payment.rb
class CreditCardPayment < Payment

end	

app/models/dish.rb
class Dish < ActiveRecord::Base
  attr_accessible :description, :notes, :number, :price, :title

  has_many :orders, as: :item

end

app/models/drink.rb
class Drink < ActiveRecord::Base
  attr_accessible :alcoholic, :number, :price, :size, :title

  has_many :orders, as: :item

end

app/models/guest.rb
# -*- encoding : utf-8 -*-
class Guest < ActiveRecord::Base
  attr_accessible :address, :city, :country, :email, :first_name, :last_name, :postal, :telefon

  has_many :reservations
  has_many :orders
  has_many :bills
  has_many :payments, through: :bills


  def fullname
  	"#{first_name} #{last_name}"
  end	


end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :bill_id, :cancelled, :discount, :guest_id, :item_id, :item_type, :position, :price, :reservation_id, :product_name

  belongs_to :guest
  belongs_to :reservation
  belongs_to :bill

  belongs_to :item, polymorphic: true

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  attr_accessible :bill_id, :card_number, :card_provider, :card_valid_until, :paid_at, :total, :type

  belongs_to :bill
  has_one :guest, through: :bill

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  attr_accessible :duration, :guest_id, :notes, :priority, :reservation_date, :special_service

  belongs_to :guest
  has_one :table
  has_many :orders
  

end

app/models/table.rb
class Table < ActiveRecord::Base
  attr_accessible :exclusive, :number, :reservation_id, :seats, :taken

  belongs_to :reservation

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.json
  def new
    @bill = Bill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render json: @bill, status: :created, location: @bill }
      else
        format.html { render action: "new" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.json
  def update
    @bill = Bill.find(params[:id])

    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
# -*- encoding : utf-8 -*-
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/guests_helper.rb
# -*- encoding : utf-8 -*-
module GuestsHelper
end

app/helpers/home_helper.rb
# -*- encoding : utf-8 -*-
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/payments/_form.html.erb
<%= simple_form_for(@payment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :bill_id %>
    <%= f.input :type %>
    <%= f.input :total %>
    <%= f.input :paid_at %>
    <%= f.input :card_number %>
    <%= f.input :card_valid_until %>
    <%= f.input :card_provider %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th>Bill</th>
    <th>Type</th>
    <th>Total</th>
    <th>Paid at</th>
    <th>Card number</th>
    <th>Card valid until</th>
    <th>Card provider</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.bill_id %></td>
    <td><%= payment.type %></td>
    <td><%= payment.total %></td>
    <td><%= payment.paid_at %></td>
    <td><%= payment.card_number %></td>
    <td><%= payment.card_valid_until %></td>
    <td><%= payment.card_provider %></td>
    <td><%= link_to 'Show', payment_path(payment) %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bill:</b>
  <%= @payment.bill_id %>
</p>

<p>
  <b>Type:</b>
  <%= @payment.type %>
</p>

<p>
  <b>Total:</b>
  <%= @payment.total %>
</p>

<p>
  <b>Paid at:</b>
  <%= @payment.paid_at %>
</p>

<p>
  <b>Card number:</b>
  <%= @payment.card_number %>
</p>

<p>
  <b>Card valid until:</b>
  <%= @payment.card_valid_until %>
</p>

<p>
  <b>Card provider:</b>
  <%= @payment.card_provider %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>